<x-app-layout>
    <style>[x-cloak] { display: none !important; }</style>
    <x-slot name="header"><div><p class="text-xs font-semibold uppercase tracking-[0.2em] text-amber-700">Hotel administration</p><h2 class="mt-1 text-2xl font-semibold text-stone-900">Catalog</h2></div></x-slot>

    <div x-data="{ tab: 'amenities' }" class="min-h-screen bg-stone-50 py-8">
        <div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8">
            @if(session('status'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-medium text-emerald-800">{{ session('status') }}</div>@endif

            <div class="flex flex-wrap gap-2 rounded-xl border border-stone-200 bg-white p-2 shadow-sm">
                @foreach(['amenities' => 'Amenities', 'services' => 'Services', 'rates' => 'Rate plans', 'coupons' => 'Coupons'] as $key => $label)
                    <button type="button" @click="tab = '{{ $key }}'" class="rounded-lg px-4 py-2.5 text-sm font-semibold transition" :class="tab === '{{ $key }}' ? 'bg-amber-400 text-stone-950' : 'text-stone-500 hover:bg-stone-100 hover:text-stone-900'">{{ $label }}</button>
                @endforeach
            </div>

            <section x-show="tab === 'amenities'" x-cloak class="grid gap-6 lg:grid-cols-[minmax(0,360px)_1fr]">
                <div class="rounded-xl border border-stone-200 bg-white p-6 shadow-sm"><p class="text-xs font-semibold uppercase tracking-widest text-amber-700">Room features</p><h3 class="mt-2 text-xl font-semibold">Add an amenity</h3><p class="mt-2 text-sm leading-6 text-stone-500">Manage the features guests can see on room types.</p><form method="post" action="{{ route('admin.catalog.amenities.store') }}" class="mt-6 grid gap-3">@csrf<input required name="name" placeholder="Amenity name" class="rounded-lg border-stone-300"><input required name="slug" placeholder="Slug" class="rounded-lg border-stone-300"><button class="rounded-lg bg-stone-900 px-4 py-3 font-semibold text-white hover:bg-amber-700">Add amenity</button></form></div>
                <div class="rounded-xl border border-stone-200 bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><div><h3 class="text-xl font-semibold">Current amenities</h3><p class="mt-1 text-sm text-stone-500">{{ $amenities->count() }} available features</p></div><span class="rounded-full bg-stone-100 px-3 py-1 text-xs font-semibold">Room catalog</span></div><div class="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@foreach($amenities as $amenity)<div class="rounded-lg border border-stone-200 p-4"><p class="font-semibold">{{ $amenity->name }}</p><p class="mt-1 text-xs text-stone-500">{{ $amenity->slug }}</p></div>@endforeach</div></div>
            </section>

            <section x-show="tab === 'services'" x-cloak class="grid gap-6 lg:grid-cols-[minmax(0,360px)_1fr]">
                <div class="rounded-xl border border-stone-200 bg-white p-6 shadow-sm"><p class="text-xs font-semibold uppercase tracking-widest text-amber-700">Guest extras</p><h3 class="mt-2 text-xl font-semibold">Add a service</h3><form method="post" action="{{ route('admin.catalog.services.store') }}" class="mt-6 grid gap-3">@csrf<input required name="name" placeholder="Service name" class="rounded-lg border-stone-300"><select name="pricing_unit" class="rounded-lg border-stone-300"><option value="per_booking">Per booking</option><option value="per_night">Per night</option><option value="per_guest">Per guest</option></select><input required name="price" type="number" min="0" step="0.01" placeholder="Price" class="rounded-lg border-stone-300"><button class="rounded-lg bg-stone-900 px-4 py-3 font-semibold text-white hover:bg-amber-700">Add service</button></form></div>
                <div class="rounded-xl border border-stone-200 bg-white p-6 shadow-sm"><h3 class="text-xl font-semibold">Service menu</h3><p class="mt-1 text-sm text-stone-500">Pause services without removing booking history.</p><div class="mt-6 space-y-3">@foreach($services as $service)<div class="flex flex-col gap-3 rounded-lg border border-stone-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="font-semibold">{{ $service->name }}</p><p class="mt-1 text-xs text-stone-500">{{ $service->pricing_unit->value }} · {{ $service->is_active ? 'Active' : 'Paused' }}</p></div><div class="flex gap-3"><form method="post" action="{{ route('admin.catalog.services.toggle', $service) }}">@csrf @method('PATCH')<button class="text-sm font-semibold text-amber-700">{{ $service->is_active ? 'Pause' : 'Resume' }}</button></form><form method="post" action="{{ route('admin.catalog.services.destroy', $service) }}" onsubmit="return confirm('Delete this service?')">@csrf @method('DELETE')<button class="text-sm font-semibold text-red-700">Delete</button></form></div></div>@endforeach</div></div>
            </section>

            <section x-show="tab === 'rates'" x-cloak class="grid gap-6 lg:grid-cols-[minmax(0,360px)_1fr]">
                <div class="rounded-xl border border-stone-200 bg-white p-6 shadow-sm"><p class="text-xs font-semibold uppercase tracking-widest text-amber-700">Pricing</p><h3 class="mt-2 text-xl font-semibold">Add a rate plan</h3><form method="post" action="{{ route('admin.catalog.rate-plans.store') }}" class="mt-6 grid gap-3">@csrf<input required name="name" placeholder="Rate name" class="rounded-lg border-stone-300"><input required name="slug" placeholder="Slug" class="rounded-lg border-stone-300"><select name="room_type_id" class="rounded-lg border-stone-300">@foreach($roomTypes as $type)<option value="{{ $type->id }}">{{ $type->name }}</option>@endforeach</select><div class="grid grid-cols-2 gap-3"><input required name="starts_on" type="date" value="{{ today()->toDateString() }}" class="rounded-lg border-stone-300"><input required name="ends_on" type="date" value="{{ today()->addYear()->toDateString() }}" class="rounded-lg border-stone-300"></div><input required name="price" type="number" min="0" step="0.01" placeholder="Nightly price" class="rounded-lg border-stone-300"><button class="rounded-lg bg-stone-900 px-4 py-3 font-semibold text-white hover:bg-amber-700">Add rate plan</button></form></div>
                <div class="rounded-xl border border-stone-200 bg-white p-6 shadow-sm"><h3 class="text-xl font-semibold">Rate plans</h3><p class="mt-1 text-sm text-stone-500">Control which rates are available to the pricing engine.</p><div class="mt-6 space-y-3">@foreach($ratePlans as $plan)<div class="flex flex-col gap-3 rounded-lg border border-stone-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="font-semibold">{{ $plan->name }}</p><p class="mt-1 text-xs text-stone-500">{{ $plan->roomRates->first()?->roomType?->name }} · {{ $plan->is_active ? 'Active' : 'Paused' }}</p></div><div class="flex gap-3"><form method="post" action="{{ route('admin.catalog.rate-plans.toggle', $plan) }}">@csrf @method('PATCH')<button class="text-sm font-semibold text-amber-700">{{ $plan->is_active ? 'Pause' : 'Resume' }}</button></form><form method="post" action="{{ route('admin.catalog.rate-plans.destroy', $plan) }}" onsubmit="return confirm('Delete this rate plan?')">@csrf @method('DELETE')<button class="text-sm font-semibold text-red-700">Delete</button></form></div></div>@endforeach</div></div>
            </section>

            <section x-show="tab === 'coupons'" x-cloak class="grid gap-6 lg:grid-cols-[minmax(0,360px)_1fr]">
                <div class="rounded-xl border border-stone-200 bg-white p-6 shadow-sm"><p class="text-xs font-semibold uppercase tracking-widest text-amber-700">Promotions</p><h3 class="mt-2 text-xl font-semibold">Create a coupon</h3><p class="mt-2 text-sm leading-6 text-stone-500">Pause a coupon to stop new use without deleting its history.</p><form method="post" action="{{ route('admin.catalog.coupons.store') }}" class="mt-6 grid gap-3">@csrf<input required name="code" placeholder="Coupon code" class="rounded-lg border-stone-300"><div class="grid grid-cols-2 gap-3"><select name="discount_type" class="rounded-lg border-stone-300"><option value="percentage">Percentage</option><option value="fixed">Fixed amount</option></select><input required name="discount_value" type="number" min="0" step="0.01" placeholder="Discount" class="rounded-lg border-stone-300"></div><div class="grid grid-cols-2 gap-3"><input required name="starts_on" type="date" value="{{ today()->toDateString() }}" class="rounded-lg border-stone-300"><input required name="ends_on" type="date" value="{{ today()->addMonths(6)->toDateString() }}" class="rounded-lg border-stone-300"></div><button class="rounded-lg bg-stone-900 px-4 py-3 font-semibold text-white hover:bg-amber-700">Create coupon</button></form></div>
                <div class="rounded-xl border border-stone-200 bg-white p-6 shadow-sm"><h3 class="text-xl font-semibold">Promotion codes</h3><p class="mt-1 text-sm text-stone-500">Manage active offers and stop them instantly.</p><div class="mt-6 space-y-3">@foreach($coupons as $coupon)<div class="flex flex-col gap-3 rounded-lg border border-stone-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="font-semibold tracking-wide">{{ $coupon->code }}</p><p class="mt-1 text-xs text-stone-500">{{ $coupon->discount_type }} · {{ $coupon->is_active ? 'Active' : 'Paused' }} · ends {{ $coupon->ends_on->format('M d, Y') }}</p></div><div class="flex gap-3"><form method="post" action="{{ route('admin.catalog.coupons.toggle', $coupon) }}">@csrf @method('PATCH')<button class="text-sm font-semibold text-amber-700">{{ $coupon->is_active ? 'Pause' : 'Resume' }}</button></form><form method="post" action="{{ route('admin.catalog.coupons.destroy', $coupon) }}" onsubmit="return confirm('Delete this coupon?')">@csrf @method('DELETE')<button class="text-sm font-semibold text-red-700">Delete</button></form></div></div>@endforeach</div></div>
            </section>
        </div>
    </div>
</x-app-layout>
