<x-app-layout>
    <x-slot name="header"><div class="flex items-end justify-between"><div><p class="text-xs font-semibold uppercase tracking-[0.2em] text-amber-700">Inventory control</p><h2 class="mt-1 text-2xl font-semibold text-stone-900">Room types</h2></div><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">{{ $roomTypeCounts['active'] }} active types</span></div></x-slot>

    <div class="min-h-screen bg-stone-50 py-8"><div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8">
        @if (session('status'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-medium text-emerald-800">{{ session('status') }}</div>@endif

        <div class="grid gap-4 sm:grid-cols-3"><div class="rounded-xl border border-stone-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-widest text-stone-500">Room types</p><p class="mt-3 text-3xl font-semibold">{{ $roomTypeCounts['total'] }}</p></div><div class="rounded-xl border border-stone-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-widest text-stone-500">Active types</p><p class="mt-3 text-3xl font-semibold">{{ $roomTypeCounts['active'] }}</p></div><div class="rounded-xl border border-stone-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-widest text-stone-500">Physical rooms</p><p class="mt-3 text-3xl font-semibold">{{ $roomTypeCounts['rooms'] }}</p></div></div>

        <section class="rounded-2xl border border-stone-200 bg-white p-6 shadow-sm"><div><p class="text-xs font-semibold uppercase tracking-widest text-amber-700">Inventory action</p><h3 class="mt-1 text-xl font-semibold">Add a room type</h3><p class="mt-1 text-sm text-stone-500">Define the sellable category guests choose during booking.</p></div><form method="post" action="{{ route('admin.inventory.room-types.store') }}" class="mt-6 grid gap-3 md:grid-cols-4">@csrf<input name="hotel_id" required value="{{ $hotels->first()?->id }}" type="hidden"><input name="name" required placeholder="Name" class="rounded-lg border-stone-300"><input name="slug" required placeholder="Slug" class="rounded-lg border-stone-300"><input name="base_price" required type="number" min="0" step="0.01" placeholder="Base price" class="rounded-lg border-stone-300"><input name="max_adults" required type="number" min="1" placeholder="Max adults" class="rounded-lg border-stone-300"><input name="max_children" required type="number" min="0" placeholder="Max children" class="rounded-lg border-stone-300"><input name="max_occupancy" required type="number" min="1" placeholder="Max occupancy" class="rounded-lg border-stone-300"><input name="bed_configuration" placeholder="Bed configuration" class="rounded-lg border-stone-300"><button class="rounded-lg bg-stone-900 px-5 py-3 text-sm font-semibold text-white hover:bg-amber-700">Create room type</button></form></section>

        <section class="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm"><div class="border-b border-stone-200 p-6"><h3 class="text-xl font-semibold">Room type inventory</h3><p class="mt-1 text-sm text-stone-500">Manage categories, rates, capacity, and room imagery.</p></div><div class="divide-y">@foreach($roomTypes as $roomType)<article class="flex flex-col gap-5 p-6 lg:flex-row lg:items-center lg:justify-between"><div class="flex items-start gap-4"><div class="flex h-14 w-14 items-center justify-center rounded-xl bg-amber-100 text-xl font-semibold text-amber-800">{{ strtoupper(substr($roomType->name, 0, 1)) }}</div><div><div class="flex items-center gap-3"><h4 class="text-lg font-semibold">{{ $roomType->name }}</h4><span class="rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-widest {{ $roomType->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-stone-100 text-stone-500' }}">{{ $roomType->is_active ? 'Active' : 'Inactive' }}</span></div><p class="mt-2 text-sm text-stone-500">{{ $roomType->rooms_count }} physical rooms · {{ $roomType->max_adults }} adults · {{ $roomType->max_children }} children · up to {{ $roomType->max_occupancy }} guests</p><p class="mt-1 text-sm font-semibold text-stone-700">${{ number_format($roomType->base_price, 2) }} <span class="font-normal text-stone-400">base nightly rate</span></p></div></div><form method="post" action="{{ route('admin.inventory.room-types.images.store', $roomType) }}" enctype="multipart/form-data" class="flex flex-col gap-2 sm:flex-row sm:items-center">@csrf<label class="text-xs font-semibold text-stone-500">Room image<input required type="file" name="image" accept="image/jpeg,image/png,image/webp" class="mt-1 block max-w-52 text-xs"></label><button class="rounded-lg border border-stone-300 px-4 py-2 text-xs font-semibold hover:border-amber-500">Upload</button></form></article>@endforeach</div><div class="border-t border-stone-100 p-6">{{ $roomTypes->links() }}</div></section>
    </div></div>
</x-app-layout>
