<x-app-layout>
    <x-slot name="header"><div class="flex items-end justify-between"><div><p class="text-xs font-semibold uppercase tracking-[0.2em] text-amber-700">Inventory control</p><h2 class="mt-1 text-2xl font-semibold text-stone-900">Rooms</h2></div><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">{{ $rooms->total() }} total rooms</span></div></x-slot>

    <div x-data="{ query: '' }" class="min-h-screen bg-stone-50 py-8"><div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8">
        @if (session('status'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-medium text-emerald-800">{{ session('status') }}</div>@endif

        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            @foreach(['available' => ['Available', 'bg-emerald-500'], 'reserved' => ['Reserved', 'bg-amber-400'], 'occupied' => ['Occupied', 'bg-blue-500'], 'maintenance' => ['Maintenance', 'bg-rose-500']] as $key => $card)
                <div class="rounded-xl border border-stone-200 bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><p class="text-xs font-semibold uppercase tracking-widest text-stone-500">{{ $card[0] }}</p><span class="h-2.5 w-2.5 rounded-full {{ $card[1] }}"></span></div><p class="mt-3 text-3xl font-semibold">{{ $key === 'maintenance' ? ($roomCounts['maintenance'] ?? 0) + ($roomCounts['out_of_order'] ?? 0) : ($roomCounts[$key] ?? 0) }}</p></div>
            @endforeach
        </div>

        <section class="rounded-2xl border border-stone-200 bg-white p-6 shadow-sm"><div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-xs font-semibold uppercase tracking-widest text-amber-700">Inventory action</p><h3 class="mt-1 text-xl font-semibold">Add a physical room</h3><p class="mt-1 text-sm text-stone-500">Create a sellable room and assign its operational state.</p></div></div><form method="post" action="{{ route('admin.inventory.rooms.store') }}" class="mt-6 grid gap-3 md:grid-cols-[1.2fr_1fr_.7fr_1fr_auto]">@csrf<select name="room_type_id" required class="rounded-lg border-stone-300 bg-white"><option value="">Room type</option>@foreach($roomTypes as $type)<option value="{{ $type->id }}">{{ $type->name }}</option>@endforeach</select><input name="room_number" required placeholder="Room number" class="rounded-lg border-stone-300"><input name="floor" type="number" min="0" placeholder="Floor" class="rounded-lg border-stone-300"><select name="status" class="rounded-lg border-stone-300 bg-white">@foreach($statuses as $status)<option value="{{ $status->value }}">{{ str_replace('_', ' ', ucfirst($status->value)) }}</option>@endforeach</select><button class="rounded-lg bg-stone-900 px-5 py-3 text-sm font-semibold text-white hover:bg-amber-700">Create room</button></form></section>

        <section class="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm"><div class="flex flex-col gap-4 border-b border-stone-200 p-6 sm:flex-row sm:items-center sm:justify-between"><div><h3 class="text-xl font-semibold">Physical room board</h3><p class="mt-1 text-sm text-stone-500">Scan every room’s current operating status.</p></div><label class="relative"><span class="sr-only">Search rooms</span><input x-model="query" placeholder="Search room or type" class="w-full rounded-lg border-stone-300 pl-4 pr-4 text-sm sm:w-64"></label></div><div class="grid gap-3 p-6 sm:grid-cols-2 lg:grid-cols-4">@foreach($rooms as $room)<article x-show="'{{ strtolower($room->room_number.' '.$room->roomType->name) }}'.includes(query.toLowerCase())" class="rounded-xl border border-stone-200 p-4 transition hover:border-amber-300 hover:shadow-sm"><div class="flex items-center justify-between"><p class="text-lg font-semibold">{{ $room->room_number }}</p><span class="rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-widest {{ in_array($room->status->value, ['available', 'clean']) ? 'bg-emerald-50 text-emerald-700' : (in_array($room->status->value, ['maintenance', 'out_of_order']) ? 'bg-rose-50 text-rose-700' : 'bg-amber-50 text-amber-700') }}">{{ str_replace('_', ' ', $room->status->value) }}</span></div><p class="mt-3 text-sm text-stone-600">{{ $room->roomType->name }}</p><p class="mt-1 text-xs text-stone-400">Floor {{ $room->floor ?? '—' }}</p></article>@endforeach</div><div class="border-t border-stone-100 p-6">{{ $rooms->links() }}</div></section>
    </div></div>
</x-app-layout>
